using System;

// Token: 0x02000207 RID: 519
public static class UberShaderKeywords
{
	// Token: 0x04000E98 RID: 3736
	public const string STEREO_INSTANCING_ON = "STEREO_INSTANCING_ON";

	// Token: 0x04000E99 RID: 3737
	public const string UNITY_SINGLE_PASS_STEREO = "UNITY_SINGLE_PASS_STEREO";

	// Token: 0x04000E9A RID: 3738
	public const string STEREO_MULTIVIEW_ON = "STEREO_MULTIVIEW_ON";

	// Token: 0x04000E9B RID: 3739
	public const string STEREO_CUBEMAP_RENDER_ON = "STEREO_CUBEMAP_RENDER_ON";

	// Token: 0x04000E9C RID: 3740
	public const string _GLOBAL_ZONE_LIQUID_TYPE__WATER = "_GLOBAL_ZONE_LIQUID_TYPE__WATER";

	// Token: 0x04000E9D RID: 3741
	public const string _GLOBAL_ZONE_LIQUID_TYPE__LAVA = "_GLOBAL_ZONE_LIQUID_TYPE__LAVA";

	// Token: 0x04000E9E RID: 3742
	public const string _ZONE_LIQUID_SHAPE__CYLINDER = "_ZONE_LIQUID_SHAPE__CYLINDER";

	// Token: 0x04000E9F RID: 3743
	public const string _USE_TEXTURE = "_USE_TEXTURE";

	// Token: 0x04000EA0 RID: 3744
	public const string USE_TEXTURE__AS_MASK = "USE_TEXTURE__AS_MASK";

	// Token: 0x04000EA1 RID: 3745
	public const string _USE_WEATHER_MAP = "_USE_WEATHER_MAP";

	// Token: 0x04000EA2 RID: 3746
	public const string _ALPHA_DETAIL_MAP = "_ALPHA_DETAIL_MAP";

	// Token: 0x04000EA3 RID: 3747
	public const string _WATER_EFFECT = "_WATER_EFFECT";

	// Token: 0x04000EA4 RID: 3748
	public const string _HEIGHT_BASED_WATER_EFFECT = "_HEIGHT_BASED_WATER_EFFECT";

	// Token: 0x04000EA5 RID: 3749
	public const string _ALPHATEST_ON = "_ALPHATEST_ON";

	// Token: 0x04000EA6 RID: 3750
	public const string _MAINTEX_ROTATE = "_MAINTEX_ROTATE";

	// Token: 0x04000EA7 RID: 3751
	public const string _UV_WAVE_WARP = "_UV_WAVE_WARP";

	// Token: 0x04000EA8 RID: 3752
	public const string _LIQUID_VOLUME = "_LIQUID_VOLUME";

	// Token: 0x04000EA9 RID: 3753
	public const string _LIQUID_CONTAINER = "_LIQUID_CONTAINER";

	// Token: 0x04000EAA RID: 3754
	public const string _EMISSION = "_EMISSION";

	// Token: 0x04000EAB RID: 3755
	public const string _EMISSION_USE_UV_WAVE_WARP = "_EMISSION_USE_UV_WAVE_WARP";

	// Token: 0x04000EAC RID: 3756
	public const string _USE_DEFORM_MAP = "_USE_DEFORM_MAP";

	// Token: 0x04000EAD RID: 3757
	public const string _USE_DAY_NIGHT_LIGHTMAP = "_USE_DAY_NIGHT_LIGHTMAP";

	// Token: 0x04000EAE RID: 3758
	public const string _USE_TEX_ARRAY_ATLAS = "_USE_TEX_ARRAY_ATLAS";

	// Token: 0x04000EAF RID: 3759
	public const string _CRYSTAL_EFFECT = "_CRYSTAL_EFFECT";

	// Token: 0x04000EB0 RID: 3760
	public const string _EYECOMP = "_EYECOMP";

	// Token: 0x04000EB1 RID: 3761
	public const string _MOUTHCOMP = "_MOUTHCOMP";

	// Token: 0x04000EB2 RID: 3762
	public const string _ALPHA_BLUE_LIVE_ON = "_ALPHA_BLUE_LIVE_ON";

	// Token: 0x04000EB3 RID: 3763
	public const string _GRID_EFFECT = "_GRID_EFFECT";

	// Token: 0x04000EB4 RID: 3764
	public const string _REFLECTIONS = "_REFLECTIONS";

	// Token: 0x04000EB5 RID: 3765
	public const string _REFLECTIONS_BOX_PROJECT = "_REFLECTIONS_BOX_PROJECT";

	// Token: 0x04000EB6 RID: 3766
	public const string _REFLECTIONS_USE_NORMAL_TEX = "_REFLECTIONS_USE_NORMAL_TEX";

	// Token: 0x04000EB7 RID: 3767
	public const string _VERTEX_ROTATE = "_VERTEX_ROTATE";

	// Token: 0x04000EB8 RID: 3768
	public const string _VERTEX_ANIM_FLAP = "_VERTEX_ANIM_FLAP";

	// Token: 0x04000EB9 RID: 3769
	public const string _VERTEX_ANIM_WAVE = "_VERTEX_ANIM_WAVE";

	// Token: 0x04000EBA RID: 3770
	public const string _VERTEX_ANIM_WAVE_DEBUG = "_VERTEX_ANIM_WAVE_DEBUG";

	// Token: 0x04000EBB RID: 3771
	public const string _VERTEX_LIGHTING = "_VERTEX_LIGHTING";

	// Token: 0x04000EBC RID: 3772
	public const string _GRADIENT_MAP_ON = "_GRADIENT_MAP_ON";

	// Token: 0x04000EBD RID: 3773
	public const string _PARALLAX = "_PARALLAX";

	// Token: 0x04000EBE RID: 3774
	public const string _PARALLAX_AA = "_PARALLAX_AA";

	// Token: 0x04000EBF RID: 3775
	public const string _PARALLAX_PLANAR = "_PARALLAX_PLANAR";

	// Token: 0x04000EC0 RID: 3776
	public const string _MASK_MAP_ON = "_MASK_MAP_ON";

	// Token: 0x04000EC1 RID: 3777
	public const string _FX_LAVA_LAMP = "_FX_LAVA_LAMP";

	// Token: 0x04000EC2 RID: 3778
	public const string _INNER_GLOW = "_INNER_GLOW";

	// Token: 0x04000EC3 RID: 3779
	public const string _STEALTH_EFFECT = "_STEALTH_EFFECT";

	// Token: 0x04000EC4 RID: 3780
	public const string _UV_SHIFT = "_UV_SHIFT";

	// Token: 0x04000EC5 RID: 3781
	public const string _TEXEL_SNAP_UVS = "_TEXEL_SNAP_UVS";

	// Token: 0x04000EC6 RID: 3782
	public const string _UNITY_EDIT_MODE = "_UNITY_EDIT_MODE";

	// Token: 0x04000EC7 RID: 3783
	public const string _GT_EDITOR_TIME = "_GT_EDITOR_TIME";

	// Token: 0x04000EC8 RID: 3784
	public const string _DEBUG_PAWN_DATA = "_DEBUG_PAWN_DATA";

	// Token: 0x04000EC9 RID: 3785
	public const string _COLOR_GRADE_PROTANOMALY = "_COLOR_GRADE_PROTANOMALY";

	// Token: 0x04000ECA RID: 3786
	public const string _COLOR_GRADE_PROTANOPIA = "_COLOR_GRADE_PROTANOPIA";

	// Token: 0x04000ECB RID: 3787
	public const string _COLOR_GRADE_DEUTERANOMALY = "_COLOR_GRADE_DEUTERANOMALY";

	// Token: 0x04000ECC RID: 3788
	public const string _COLOR_GRADE_DEUTERANOPIA = "_COLOR_GRADE_DEUTERANOPIA";

	// Token: 0x04000ECD RID: 3789
	public const string _COLOR_GRADE_TRITANOMALY = "_COLOR_GRADE_TRITANOMALY";

	// Token: 0x04000ECE RID: 3790
	public const string _COLOR_GRADE_TRITANOPIA = "_COLOR_GRADE_TRITANOPIA";

	// Token: 0x04000ECF RID: 3791
	public const string _COLOR_GRADE_ACHROMATOMALY = "_COLOR_GRADE_ACHROMATOMALY";

	// Token: 0x04000ED0 RID: 3792
	public const string _COLOR_GRADE_ACHROMATOPSIA = "_COLOR_GRADE_ACHROMATOPSIA";

	// Token: 0x04000ED1 RID: 3793
	public const string LIGHTMAP_ON = "LIGHTMAP_ON";

	// Token: 0x04000ED2 RID: 3794
	public const string DIRLIGHTMAP_COMBINED = "DIRLIGHTMAP_COMBINED";

	// Token: 0x04000ED3 RID: 3795
	public const string INSTANCING_ON = "INSTANCING_ON";

	// Token: 0x04000ED4 RID: 3796
	public static readonly string[] namesArray = new string[]
	{
		"STEREO_INSTANCING_ON", "UNITY_SINGLE_PASS_STEREO", "STEREO_MULTIVIEW_ON", "STEREO_CUBEMAP_RENDER_ON", "_GLOBAL_ZONE_LIQUID_TYPE__WATER", "_GLOBAL_ZONE_LIQUID_TYPE__LAVA", "_ZONE_LIQUID_SHAPE__CYLINDER", "_USE_TEXTURE", "USE_TEXTURE__AS_MASK", "_USE_WEATHER_MAP",
		"_ALPHA_DETAIL_MAP", "_WATER_EFFECT", "_HEIGHT_BASED_WATER_EFFECT", "_ALPHATEST_ON", "_MAINTEX_ROTATE", "_UV_WAVE_WARP", "_LIQUID_VOLUME", "_LIQUID_CONTAINER", "_EMISSION", "_EMISSION_USE_UV_WAVE_WARP",
		"_USE_DEFORM_MAP", "_USE_DAY_NIGHT_LIGHTMAP", "_USE_TEX_ARRAY_ATLAS", "_CRYSTAL_EFFECT", "_EYECOMP", "_MOUTHCOMP", "_ALPHA_BLUE_LIVE_ON", "_GRID_EFFECT", "_REFLECTIONS", "_REFLECTIONS_BOX_PROJECT",
		"_REFLECTIONS_USE_NORMAL_TEX", "_VERTEX_ROTATE", "_VERTEX_ANIM_FLAP", "_VERTEX_ANIM_WAVE", "_VERTEX_ANIM_WAVE_DEBUG", "_VERTEX_LIGHTING", "_GRADIENT_MAP_ON", "_PARALLAX", "_PARALLAX_AA", "_PARALLAX_PLANAR",
		"_MASK_MAP_ON", "_FX_LAVA_LAMP", "_INNER_GLOW", "_STEALTH_EFFECT", "_UV_SHIFT", "_TEXEL_SNAP_UVS", "_UNITY_EDIT_MODE", "_GT_EDITOR_TIME", "_DEBUG_PAWN_DATA", "_COLOR_GRADE_PROTANOMALY",
		"_COLOR_GRADE_PROTANOPIA", "_COLOR_GRADE_DEUTERANOMALY", "_COLOR_GRADE_DEUTERANOPIA", "_COLOR_GRADE_TRITANOMALY", "_COLOR_GRADE_TRITANOPIA", "_COLOR_GRADE_ACHROMATOMALY", "_COLOR_GRADE_ACHROMATOPSIA", "LIGHTMAP_ON", "DIRLIGHTMAP_COMBINED", "INSTANCING_ON"
	};
}
