using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;
using Fusion;
using Unity.Burst;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: NetworkAssemblyWeaved]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.New_00003402$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Add_00003403$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Sub_00003404$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Mul_00003405$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Div_00003406$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Unm_00003407$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Eq_00003408$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Dot_0000340A$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Cross_0000340B$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Project_0000340C$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Length_0000340D$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Normalize_0000340E$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.SafeNormal_0000340F$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Distance_00003410$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Lerp_00003411$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Rotate_00003412$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.ZeroVector_00003413$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.OneVector_00003414$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.New_00003415$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Mul_00003416$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Eq_00003417$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.FromEuler_00003419$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.FromDirection_0000341A$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.GetUpVector_0000341B$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Euler_0000341C$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.Index_0000341F$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.NewIndex_00003420$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.NameCall_00003421$BurstDirectCall))]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
